"""Execution plane — isolated candidate/test execution.

Goal 02 wires the actual test run. The isolation contract from Goal 01 is fixed:
candidate code runs in a temp dir, with a hard subprocess timeout, no network, and
an environment scrubbed of credentials (``docs/05_evaluation_and_safety_gates.md``).

The controller — never a model — decides what fixed command runs here. The model
only produces the candidate *text*; this module writes it to disk and runs the
**fixed** test suite copied from the task directory. The candidate never supplies
the tests, so it cannot weaken or delete them.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from tempfile import TemporaryDirectory
from xml.etree import ElementTree

from .backends import GuardBackend, ResourceLimits, get_backend
from .safety import assert_execution_plane_isolated, scrub_execution_env

#: Written into the sandbox temp dir and loaded at interpreter startup (it sits on
#: PYTHONPATH). It neutralizes outbound network connections inside the execution
#: plane — defense in depth behind the scrubbed env and temp-dir isolation.
_SITECUSTOMIZE = """\
# Auto-generated by siro.sandbox: block outbound network in the execution plane.
import socket as _socket


def _blocked(self, *args, **kwargs):
    raise OSError("network access is disabled in the siro execution plane")


_socket.socket.connect = _blocked
_socket.socket.connect_ex = _blocked
"""


@dataclass(frozen=True)
class SandboxConfig:
    """Execution-plane limits. ``network`` is always disabled in the execution plane.

    ``backend`` selects the resource-isolation backend for guarded runs (Goal 15):
    ``"local"`` is the portable developer fallback; ``"linux_guarded"`` is hard, OS-enforced
    cgroup isolation. The backend is a control-plane choice — a candidate never selects it.
    """

    timeout_seconds: float = 10.0
    network: str = "disabled"
    max_output_bytes: int = 1_000_000
    backend: str = "local"


@dataclass(frozen=True)
class SandboxResult:
    """Raw, objective output of one sandboxed test run. Scoring happens in ``evaluator``."""

    returncode: int
    stdout: str
    stderr: str
    runtime_ms: float
    passed_tests: int
    failed_tests: int
    timed_out: bool = False
    error: str = ""

    @property
    def ran(self) -> bool:
        """True if the fixed suite actually executed (a reproducible quality signal).

        Timeouts and collection/import errors (carried in ``error``) are *not*
        reproducible signals — a candidate that can't even be collected has no
        meaningful runtime to compare, only a uniformly bad score.
        """
        return not self.timed_out and not self.error and (self.passed_tests + self.failed_tests) > 0


@dataclass(frozen=True)
class TrainingRun:
    """Raw, objective output of one sandboxed *training* run (Goal 06).

    The training analogue of :class:`SandboxResult`: scoring/promotion logic lives in
    ``training``. ``metrics`` is the JSON the fixed training script printed (val_loss,
    throughput, …); ``timed_out``/``error`` mark runs that produced no usable metric.
    """

    metrics: dict = field(default_factory=dict)
    runtime_ms: float = 0.0
    timed_out: bool = False
    error: str = ""

    @property
    def ran(self) -> bool:
        """True if the fixed training script produced a usable validation metric."""
        return not self.timed_out and not self.error and "val_loss" in self.metrics


@dataclass(frozen=True)
class ResearchRun:
    """Raw, objective output of one sandboxed *research-task* evaluation (Goal 09).

    The generic analogue of :class:`SandboxResult`/:class:`TrainingRun`: a research task's
    own ``eval.py`` is the authority, and it prints a JSON metric record (primary +
    secondary + ``passed``) on its last stdout line. ``metrics`` is that parsed object;
    ``timed_out``/``error`` mark runs that produced no usable record. Scoring/promotion
    logic lives in ``research``; this only carries the objective measurement.
    """

    metrics: dict = field(default_factory=dict)
    runtime_ms: float = 0.0
    timed_out: bool = False
    error: str = ""

    @property
    def ran(self) -> bool:
        """True if ``eval.py`` produced a usable metric record (a ``primary`` value)."""
        return (
            not self.timed_out
            and not self.error
            and "primary" in self.metrics
            and "error" not in self.metrics
        )


@dataclass(frozen=True)
class GuardedRun:
    """Output of one *resource-guarded* sandboxed evaluation (Goal 11).

    Like :class:`ResearchRun`, but executed under an explicit compute budget through a
    resource-isolation backend (Goal 15): a hard wall-clock deadline, a memory ceiling, and a
    process-count ceiling. ``timed_out`` / ``memory_exceeded`` / ``process_exceeded`` mark
    which ceiling was breached (which the caller turns into a halt-and-escalate);
    ``peak_memory_mb`` is the observed peak and ``backend`` records which backend enforced the
    limits — both for audit.
    """

    metrics: dict = field(default_factory=dict)
    runtime_ms: float = 0.0
    timed_out: bool = False
    memory_exceeded: bool = False
    process_exceeded: bool = False
    peak_memory_mb: float = 0.0
    backend: str = "local"
    error: str = ""

    @property
    def ran(self) -> bool:
        return (
            not self.timed_out
            and not self.memory_exceeded
            and not self.process_exceeded
            and not self.error
            and "primary" in self.metrics
            and "error" not in self.metrics
        )


def _truncate(text: str, limit: int) -> str:
    return text if len(text) <= limit else text[:limit] + "\n...[truncated]"


def _count_expected_tests(tests_path: Path) -> int:
    """Cheap upper bound on the number of tests, by counting ``def test_`` lines.

    Used as the failure count when a candidate can't even be collected (e.g. a
    syntax error), so a broken candidate scores below one that runs and fails.
    """
    try:
        text = tests_path.read_text(encoding="utf-8")
    except OSError:
        return 0
    return len(re.findall(r"^\s*def\s+test_\w+", text, flags=re.MULTILINE))


def _parse_junit(report_path: Path) -> tuple[int, int] | None:
    """Return ``(passed, failed)`` parsed from a JUnit XML report, or ``None``."""
    if not report_path.exists():
        return None
    try:
        root = ElementTree.parse(report_path).getroot()
    except ElementTree.ParseError:
        return None
    suites = [root] if root.tag == "testsuite" else root.findall("testsuite")
    total = failures = errors = skipped = 0
    for suite in suites:
        total += int(suite.get("tests", 0))
        failures += int(suite.get("failures", 0))
        errors += int(suite.get("errors", 0))
        skipped += int(suite.get("skipped", 0))
    passed = total - failures - errors - skipped
    return max(passed, 0), failures + errors


class Sandbox:
    """Isolated runner for candidate code: temp dir, scrubbed env, hard timeout, no net."""

    def __init__(
        self, config: SandboxConfig | None = None, *, backend: GuardBackend | str | None = None
    ) -> None:
        self.config = config or SandboxConfig()
        if backend is None:
            self.backend: GuardBackend = get_backend(self.config.backend)
        elif isinstance(backend, str):
            self.backend = get_backend(backend)
        else:
            self.backend = backend

    def child_env(self) -> dict[str, str]:
        """Environment for a candidate subprocess: credentials scrubbed."""
        return scrub_execution_env()

    def run(self, candidate, task, tests_path=None) -> SandboxResult:  # noqa: ANN001
        """Run a candidate's tests in isolation and return a :class:`SandboxResult`.

        ``candidate`` supplies only its ``code`` (written to the task's module file);
        ``task`` supplies the fixed ``module_name``. The test suite always comes from
        a controller-chosen file on disk, never from the candidate: by default the
        task's visible ``tests_path``, or an explicit ``tests_path`` override — which
        is how the hidden-test gate runs a held-out suite the candidate never saw
        (``docs/05_evaluation_and_safety_gates.md``).
        """
        suite_path = Path(tests_path) if tests_path is not None else Path(task.tests_path)
        env = self.child_env()
        assert_execution_plane_isolated(env)  # belt-and-suspenders: never run with creds

        with TemporaryDirectory(prefix="siro-sandbox-") as tmp:
            tmpdir = Path(tmp)
            (tmpdir / f"{task.module_name}.py").write_text(candidate.code, encoding="utf-8")
            (tmpdir / "tests.py").write_text(
                suite_path.read_text(encoding="utf-8"), encoding="utf-8"
            )
            (tmpdir / "sitecustomize.py").write_text(_SITECUSTOMIZE, encoding="utf-8")
            report_path = tmpdir / "report.xml"

            # The temp dir on PYTHONPATH makes both the candidate module and the
            # network-blocking sitecustomize importable at interpreter startup.
            env["PYTHONPATH"] = str(tmpdir)
            cmd = [
                sys.executable,
                "-m",
                "pytest",
                "tests.py",
                "-p",
                "no:cacheprovider",
                "-q",
                f"--junitxml={report_path}",
            ]

            start = time.perf_counter()
            try:
                proc = subprocess.run(
                    cmd,
                    cwd=tmpdir,
                    env=env,
                    capture_output=True,
                    text=True,
                    timeout=self.config.timeout_seconds,
                )
            except subprocess.TimeoutExpired as exc:
                runtime_ms = (time.perf_counter() - start) * 1000.0
                return SandboxResult(
                    returncode=-1,
                    stdout=_truncate(exc.stdout or "", self.config.max_output_bytes),
                    stderr=_truncate(exc.stderr or "", self.config.max_output_bytes),
                    runtime_ms=runtime_ms,
                    passed_tests=0,
                    failed_tests=_count_expected_tests(suite_path),
                    timed_out=True,
                    error=f"timeout after {self.config.timeout_seconds}s",
                )
            runtime_ms = (time.perf_counter() - start) * 1000.0

            parsed = _parse_junit(report_path)
            expected = _count_expected_tests(suite_path)
            if parsed is None:
                # No report at all: count every test as failed; not a real run.
                passed, failed = 0, expected
                error = "no test report produced"
            else:
                passed, failed = parsed
                if passed == 0 and proc.returncode != 0 and failed < expected:
                    # Collection/import error (e.g. syntax error): none of the real
                    # tests ran. Count them all as failed so a broken candidate scores
                    # below any candidate that runs, and mark the run non-reproducible.
                    passed, failed = 0, expected
                    error = "collection error: candidate could not be imported"
                else:
                    error = ""

            return SandboxResult(
                returncode=proc.returncode,
                stdout=_truncate(proc.stdout, self.config.max_output_bytes),
                stderr=_truncate(proc.stderr, self.config.max_output_bytes),
                runtime_ms=runtime_ms,
                passed_tests=passed,
                failed_tests=failed,
                error=error,
            )


    def run_training(self, config: dict, budget_seconds: float, *, script_path=None) -> TrainingRun:  # noqa: ANN001
        """Run the *fixed* training script under a candidate ``config`` in isolation.

        Same execution-plane contract as :meth:`run`: a temp dir, a credential-scrubbed
        env, the network-blocking ``sitecustomize``, and a hard subprocess timeout. The
        candidate supplies only ``config`` (hyperparameters, written as data); the script
        itself is controller-owned (``training_task.py``) and never candidate-editable.

        The wall-clock budget is enforced twice: cooperatively (passed to the script as
        ``_budget_seconds`` so it stops cleanly and reports a partial result) and hard (the
        subprocess timeout = ``budget_seconds`` + grace kills a script that ignores it).
        """
        script = Path(script_path) if script_path is not None else Path(__file__).with_name("training_task.py")
        env = self.child_env()
        assert_execution_plane_isolated(env)
        payload = dict(config)
        payload["_budget_seconds"] = budget_seconds
        # Hard ceiling: a few seconds past the cooperative budget, then the kernel timeout.
        hard_timeout = budget_seconds + 5.0

        with TemporaryDirectory(prefix="siro-train-") as tmp:
            tmpdir = Path(tmp)
            run_script = tmpdir / "training_task.py"
            shutil.copyfile(script, run_script)
            (tmpdir / "sitecustomize.py").write_text(_SITECUSTOMIZE, encoding="utf-8")
            config_path = tmpdir / "config.json"
            config_path.write_text(json.dumps(payload), encoding="utf-8")

            env["PYTHONPATH"] = str(tmpdir)
            cmd = [sys.executable, str(run_script), str(config_path)]
            start = time.perf_counter()
            try:
                proc = subprocess.run(
                    cmd,
                    cwd=tmpdir,
                    env=env,
                    capture_output=True,
                    text=True,
                    timeout=hard_timeout,
                )
            except subprocess.TimeoutExpired:
                runtime_ms = (time.perf_counter() - start) * 1000.0
                return TrainingRun(
                    runtime_ms=runtime_ms,
                    timed_out=True,
                    error=f"training exceeded hard timeout of {hard_timeout}s",
                )
            runtime_ms = (time.perf_counter() - start) * 1000.0

            if proc.returncode != 0:
                return TrainingRun(
                    runtime_ms=runtime_ms,
                    error=_truncate(proc.stderr or "training script failed", self.config.max_output_bytes),
                )
            line = proc.stdout.strip().splitlines()[-1] if proc.stdout.strip() else ""
            try:
                metrics = json.loads(line)
            except (json.JSONDecodeError, IndexError):
                return TrainingRun(runtime_ms=runtime_ms, error="training produced no parseable metrics")
            if "error" in metrics:
                return TrainingRun(runtime_ms=runtime_ms, metrics=metrics, error=str(metrics["error"]))
            return TrainingRun(metrics=metrics, runtime_ms=runtime_ms)


    def run_research(
        self,
        eval_path,  # noqa: ANN001 - Path to the controller-owned eval.py
        files: dict,
        *,
        hidden_payload: str | None = None,
        budget_seconds: float = 10.0,
    ) -> ResearchRun:
        """Run a research task's fixed ``eval.py`` against candidate ``files`` in isolation.

        Same execution-plane contract as :meth:`run` / :meth:`run_training`: a temp dir, a
        credential-scrubbed env, the network-blocking ``sitecustomize``, and a hard
        subprocess timeout. Plane isolation is structural here:

        - ``eval.py`` is **controller-owned** — copied from the task directory, never
          candidate-supplied — so a candidate cannot weaken or rewrite what scores it.
        - ``files`` is the candidate's edited edit surface plus any read-only baseline
          support files (written by name into the temp dir).
        - ``hidden_payload`` (held-out data/labels the agent never saw) is written **outside**
          the candidate's working/import directory, into a separate temp dir, and its path is
          handed to ``eval.py`` only via the ``SIRO_HIDDEN_PATH`` env var. So no-leakage is
          enforced, not assumed: there is no relative ``_hidden.json`` in the candidate's cwd
          to ``open``; reading the env var from candidate code trips the safety gate's
          ``env_read`` rule, and hardcoding the absolute path trips its ``filesystem`` rule.
          The held-out labels also never enter a model prompt.

        ``eval.py`` prints a single JSON object (the metric record) on its last stdout line.
        """
        script = Path(eval_path)
        env = self.child_env()
        assert_execution_plane_isolated(env)
        hard_timeout = budget_seconds + 5.0

        with TemporaryDirectory(prefix="siro-research-") as tmp, TemporaryDirectory(
            prefix="siro-hidden-"
        ) as hidden_tmp:
            tmpdir = Path(tmp)
            run_script = tmpdir / "eval.py"
            shutil.copyfile(script, run_script)
            (tmpdir / "sitecustomize.py").write_text(_SITECUSTOMIZE, encoding="utf-8")
            for name, content in files.items():
                (tmpdir / name).write_text(content, encoding="utf-8")
            # Cooperative budget passed to the evaluator (e.g. a training task's wall clock).
            (tmpdir / "_budget.json").write_text(
                json.dumps({"budget_seconds": budget_seconds}), encoding="utf-8"
            )

            env["PYTHONPATH"] = str(tmpdir)
            if hidden_payload is not None:
                # Held-out data lives outside the candidate's cwd/import path (see above).
                hidden_path = Path(hidden_tmp) / "hidden.json"
                hidden_path.write_text(hidden_payload, encoding="utf-8")
                env["SIRO_HIDDEN_PATH"] = str(hidden_path)
            cmd = [sys.executable, str(run_script)]
            start = time.perf_counter()
            try:
                proc = subprocess.run(
                    cmd,
                    cwd=tmpdir,
                    env=env,
                    capture_output=True,
                    text=True,
                    timeout=hard_timeout,
                )
            except subprocess.TimeoutExpired:
                runtime_ms = (time.perf_counter() - start) * 1000.0
                return ResearchRun(
                    runtime_ms=runtime_ms,
                    timed_out=True,
                    error=f"evaluation exceeded hard timeout of {hard_timeout}s",
                )
            runtime_ms = (time.perf_counter() - start) * 1000.0

            if proc.returncode != 0:
                return ResearchRun(
                    runtime_ms=runtime_ms,
                    error=_truncate(proc.stderr or "eval.py failed", self.config.max_output_bytes),
                )
            line = proc.stdout.strip().splitlines()[-1] if proc.stdout.strip() else ""
            try:
                metrics = json.loads(line)
            except (json.JSONDecodeError, IndexError):
                return ResearchRun(runtime_ms=runtime_ms, error="eval.py produced no parseable metric record")
            if not isinstance(metrics, dict):
                return ResearchRun(runtime_ms=runtime_ms, error="eval.py metric record was not a JSON object")
            if "error" in metrics:
                return ResearchRun(runtime_ms=runtime_ms, metrics=metrics, error=str(metrics["error"]))
            return ResearchRun(metrics=metrics, runtime_ms=runtime_ms)

    def run_guarded(
        self,
        eval_path,  # noqa: ANN001 - Path to the controller-owned eval.py
        files: dict,
        *,
        wall_clock_seconds: float,
        memory_mb: int | None = None,
        max_processes: int | None = None,
        hidden_payload: str | None = None,
        backend: GuardBackend | None = None,
    ) -> GuardedRun:
        """Run a research ``eval.py`` under an explicit compute budget (Goal 11 / Goal 15).

        Same execution-plane contract as :meth:`run_research` — offline, credential-scrubbed
        env, network-blocking ``sitecustomize``, held-out data outside the candidate cwd via
        ``SIRO_HIDDEN_PATH`` — but the run is bounded by hard ceilings (a ``wall_clock_seconds``
        deadline, an optional ``memory_mb`` ceiling, and an optional ``max_processes`` ceiling)
        enforced by a resource-isolation ``backend`` (Goal 15). The portable ``local`` backend
        samples the whole process group; the ``linux_guarded`` backend lets the kernel enforce
        the limits via cgroups. The backend is a control-plane choice, never the candidate's,
        and larger compute never relaxes plane isolation.
        """
        active = backend or self.backend
        script = Path(eval_path)
        env = self.child_env()
        assert_execution_plane_isolated(env)

        with TemporaryDirectory(prefix="siro-scaled-") as tmp, TemporaryDirectory(
            prefix="siro-hidden-"
        ) as hidden_tmp:
            tmpdir = Path(tmp)
            run_script = tmpdir / "eval.py"
            shutil.copyfile(script, run_script)
            (tmpdir / "sitecustomize.py").write_text(_SITECUSTOMIZE, encoding="utf-8")
            for name, content in files.items():
                (tmpdir / name).write_text(content, encoding="utf-8")
            (tmpdir / "_budget.json").write_text(
                json.dumps({"budget_seconds": wall_clock_seconds}), encoding="utf-8"
            )
            env["PYTHONPATH"] = str(tmpdir)
            if hidden_payload is not None:
                hidden_path = Path(hidden_tmp) / "hidden.json"
                hidden_path.write_text(hidden_payload, encoding="utf-8")
                env["SIRO_HIDDEN_PATH"] = str(hidden_path)

            cmd = [sys.executable, str(run_script)]
            limits = ResourceLimits(
                wall_clock_seconds=wall_clock_seconds,
                memory_mb=memory_mb,
                max_processes=max_processes,
            )
            start = time.perf_counter()
            result = active.run(cmd, cwd=tmpdir, env=env, limits=limits)
            runtime_ms = (time.perf_counter() - start) * 1000.0
            peak = result.peak_memory_mb

            if result.timed_out:
                return GuardedRun(
                    runtime_ms=runtime_ms,
                    timed_out=True,
                    peak_memory_mb=peak,
                    backend=result.backend,
                    error=f"evaluation exceeded the {wall_clock_seconds:g}s wall-clock ceiling",
                )
            if result.memory_exceeded:
                return GuardedRun(
                    runtime_ms=runtime_ms,
                    memory_exceeded=True,
                    peak_memory_mb=peak,
                    backend=result.backend,
                    error=f"evaluation exceeded the {memory_mb}MB memory ceiling "
                    f"(peak {peak:.0f}MB)",
                )
            if result.process_exceeded:
                return GuardedRun(
                    runtime_ms=runtime_ms,
                    process_exceeded=True,
                    peak_memory_mb=peak,
                    backend=result.backend,
                    error=f"evaluation exceeded the {max_processes}-process ceiling",
                )
            if result.returncode != 0:
                return GuardedRun(
                    runtime_ms=runtime_ms,
                    peak_memory_mb=peak,
                    backend=result.backend,
                    error=_truncate(result.stderr or "eval.py failed", self.config.max_output_bytes),
                )
            line = result.stdout.strip().splitlines()[-1] if result.stdout.strip() else ""
            try:
                metrics = json.loads(line)
            except (json.JSONDecodeError, IndexError):
                return GuardedRun(
                    runtime_ms=runtime_ms,
                    peak_memory_mb=peak,
                    backend=result.backend,
                    error="eval.py produced no parseable metric record",
                )
            if not isinstance(metrics, dict):
                return GuardedRun(
                    runtime_ms=runtime_ms,
                    peak_memory_mb=peak,
                    backend=result.backend,
                    error="eval.py metric record was not a JSON object",
                )
            if "error" in metrics:
                return GuardedRun(
                    runtime_ms=runtime_ms,
                    metrics=metrics,
                    peak_memory_mb=peak,
                    backend=result.backend,
                    error=str(metrics["error"]),
                )
            return GuardedRun(
                metrics=metrics,
                runtime_ms=runtime_ms,
                peak_memory_mb=peak,
                backend=result.backend,
            )


__all__ = [
    "SandboxConfig",
    "SandboxResult",
    "TrainingRun",
    "ResearchRun",
    "GuardedRun",
    "Sandbox",
]
