"""Execution plane — isolated candidate/test execution.

Goal 02 wires the actual test run. The isolation contract from Goal 01 is fixed:
candidate code runs in a temp dir, with a hard subprocess timeout, no network, and
an environment scrubbed of credentials (``docs/05_evaluation_and_safety_gates.md``).

The controller — never a model — decides what fixed command runs here. The model
only produces the candidate *text*; this module writes it to disk and runs the
**fixed** test suite copied from the task directory. The candidate never supplies
the tests, so it cannot weaken or delete them.
"""

from __future__ import annotations

import re
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from tempfile import TemporaryDirectory
from xml.etree import ElementTree

from .safety import assert_execution_plane_isolated, scrub_execution_env

#: Written into the sandbox temp dir and loaded at interpreter startup (it sits on
#: PYTHONPATH). It neutralizes outbound network connections inside the execution
#: plane — defense in depth behind the scrubbed env and temp-dir isolation.
_SITECUSTOMIZE = """\
# Auto-generated by siro.sandbox: block outbound network in the execution plane.
import socket as _socket


def _blocked(self, *args, **kwargs):
    raise OSError("network access is disabled in the siro execution plane")


_socket.socket.connect = _blocked
_socket.socket.connect_ex = _blocked
"""


@dataclass(frozen=True)
class SandboxConfig:
    """Execution-plane limits. ``network`` is always disabled in the execution plane."""

    timeout_seconds: float = 10.0
    network: str = "disabled"
    max_output_bytes: int = 1_000_000


@dataclass(frozen=True)
class SandboxResult:
    """Raw, objective output of one sandboxed test run. Scoring happens in ``evaluator``."""

    returncode: int
    stdout: str
    stderr: str
    runtime_ms: float
    passed_tests: int
    failed_tests: int
    timed_out: bool = False
    error: str = ""

    @property
    def ran(self) -> bool:
        """True if the fixed suite actually executed (a reproducible quality signal).

        Timeouts and collection/import errors (carried in ``error``) are *not*
        reproducible signals — a candidate that can't even be collected has no
        meaningful runtime to compare, only a uniformly bad score.
        """
        return not self.timed_out and not self.error and (self.passed_tests + self.failed_tests) > 0


def _truncate(text: str, limit: int) -> str:
    return text if len(text) <= limit else text[:limit] + "\n...[truncated]"


def _count_expected_tests(tests_path: Path) -> int:
    """Cheap upper bound on the number of tests, by counting ``def test_`` lines.

    Used as the failure count when a candidate can't even be collected (e.g. a
    syntax error), so a broken candidate scores below one that runs and fails.
    """
    try:
        text = tests_path.read_text(encoding="utf-8")
    except OSError:
        return 0
    return len(re.findall(r"^\s*def\s+test_\w+", text, flags=re.MULTILINE))


def _parse_junit(report_path: Path) -> tuple[int, int] | None:
    """Return ``(passed, failed)`` parsed from a JUnit XML report, or ``None``."""
    if not report_path.exists():
        return None
    try:
        root = ElementTree.parse(report_path).getroot()
    except ElementTree.ParseError:
        return None
    suites = [root] if root.tag == "testsuite" else root.findall("testsuite")
    total = failures = errors = skipped = 0
    for suite in suites:
        total += int(suite.get("tests", 0))
        failures += int(suite.get("failures", 0))
        errors += int(suite.get("errors", 0))
        skipped += int(suite.get("skipped", 0))
    passed = total - failures - errors - skipped
    return max(passed, 0), failures + errors


class Sandbox:
    """Isolated runner for candidate code: temp dir, scrubbed env, hard timeout, no net."""

    def __init__(self, config: SandboxConfig | None = None) -> None:
        self.config = config or SandboxConfig()

    def child_env(self) -> dict[str, str]:
        """Environment for a candidate subprocess: credentials scrubbed."""
        return scrub_execution_env()

    def run(self, candidate, task) -> SandboxResult:  # noqa: ANN001
        """Run a candidate's tests in isolation and return a :class:`SandboxResult`.

        ``candidate`` supplies only its ``code`` (written to the task's module file);
        ``task`` supplies the fixed ``tests_path`` and importable ``module_name``. The
        test suite always comes from the task directory, never from the candidate.
        """
        env = self.child_env()
        assert_execution_plane_isolated(env)  # belt-and-suspenders: never run with creds

        with TemporaryDirectory(prefix="siro-sandbox-") as tmp:
            tmpdir = Path(tmp)
            (tmpdir / f"{task.module_name}.py").write_text(candidate.code, encoding="utf-8")
            (tmpdir / "tests.py").write_text(
                Path(task.tests_path).read_text(encoding="utf-8"), encoding="utf-8"
            )
            (tmpdir / "sitecustomize.py").write_text(_SITECUSTOMIZE, encoding="utf-8")
            report_path = tmpdir / "report.xml"

            # The temp dir on PYTHONPATH makes both the candidate module and the
            # network-blocking sitecustomize importable at interpreter startup.
            env["PYTHONPATH"] = str(tmpdir)
            cmd = [
                sys.executable,
                "-m",
                "pytest",
                "tests.py",
                "-p",
                "no:cacheprovider",
                "-q",
                f"--junitxml={report_path}",
            ]

            start = time.perf_counter()
            try:
                proc = subprocess.run(
                    cmd,
                    cwd=tmpdir,
                    env=env,
                    capture_output=True,
                    text=True,
                    timeout=self.config.timeout_seconds,
                )
            except subprocess.TimeoutExpired as exc:
                runtime_ms = (time.perf_counter() - start) * 1000.0
                return SandboxResult(
                    returncode=-1,
                    stdout=_truncate(exc.stdout or "", self.config.max_output_bytes),
                    stderr=_truncate(exc.stderr or "", self.config.max_output_bytes),
                    runtime_ms=runtime_ms,
                    passed_tests=0,
                    failed_tests=_count_expected_tests(Path(task.tests_path)),
                    timed_out=True,
                    error=f"timeout after {self.config.timeout_seconds}s",
                )
            runtime_ms = (time.perf_counter() - start) * 1000.0

            parsed = _parse_junit(report_path)
            expected = _count_expected_tests(Path(task.tests_path))
            if parsed is None:
                # No report at all: count every test as failed; not a real run.
                passed, failed = 0, expected
                error = "no test report produced"
            else:
                passed, failed = parsed
                if passed == 0 and proc.returncode != 0 and failed < expected:
                    # Collection/import error (e.g. syntax error): none of the real
                    # tests ran. Count them all as failed so a broken candidate scores
                    # below any candidate that runs, and mark the run non-reproducible.
                    passed, failed = 0, expected
                    error = "collection error: candidate could not be imported"
                else:
                    error = ""

            return SandboxResult(
                returncode=proc.returncode,
                stdout=_truncate(proc.stdout, self.config.max_output_bytes),
                stderr=_truncate(proc.stderr, self.config.max_output_bytes),
                runtime_ms=runtime_ms,
                passed_tests=passed,
                failed_tests=failed,
                error=error,
            )


__all__ = ["SandboxConfig", "SandboxResult", "Sandbox"]
