"""Execution plane — isolated candidate/test execution.

Goal 02 wires the actual test run. The isolation contract from Goal 01 is fixed:
candidate code runs in a temp dir, with a hard subprocess timeout, no network, and
an environment scrubbed of credentials (``docs/05_evaluation_and_safety_gates.md``).

The controller — never a model — decides what fixed command runs here. The model
only produces the candidate *text*; this module writes it to disk and runs the
**fixed** test suite copied from the task directory. The candidate never supplies
the tests, so it cannot weaken or delete them.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from tempfile import TemporaryDirectory
from xml.etree import ElementTree

from .safety import assert_execution_plane_isolated, scrub_execution_env

#: Written into the sandbox temp dir and loaded at interpreter startup (it sits on
#: PYTHONPATH). It neutralizes outbound network connections inside the execution
#: plane — defense in depth behind the scrubbed env and temp-dir isolation.
_SITECUSTOMIZE = """\
# Auto-generated by siro.sandbox: block outbound network in the execution plane.
import socket as _socket


def _blocked(self, *args, **kwargs):
    raise OSError("network access is disabled in the siro execution plane")


_socket.socket.connect = _blocked
_socket.socket.connect_ex = _blocked
"""


@dataclass(frozen=True)
class SandboxConfig:
    """Execution-plane limits. ``network`` is always disabled in the execution plane."""

    timeout_seconds: float = 10.0
    network: str = "disabled"
    max_output_bytes: int = 1_000_000


@dataclass(frozen=True)
class SandboxResult:
    """Raw, objective output of one sandboxed test run. Scoring happens in ``evaluator``."""

    returncode: int
    stdout: str
    stderr: str
    runtime_ms: float
    passed_tests: int
    failed_tests: int
    timed_out: bool = False
    error: str = ""

    @property
    def ran(self) -> bool:
        """True if the fixed suite actually executed (a reproducible quality signal).

        Timeouts and collection/import errors (carried in ``error``) are *not*
        reproducible signals — a candidate that can't even be collected has no
        meaningful runtime to compare, only a uniformly bad score.
        """
        return not self.timed_out and not self.error and (self.passed_tests + self.failed_tests) > 0


@dataclass(frozen=True)
class TrainingRun:
    """Raw, objective output of one sandboxed *training* run (Goal 06).

    The training analogue of :class:`SandboxResult`: scoring/promotion logic lives in
    ``training``. ``metrics`` is the JSON the fixed training script printed (val_loss,
    throughput, …); ``timed_out``/``error`` mark runs that produced no usable metric.
    """

    metrics: dict = field(default_factory=dict)
    runtime_ms: float = 0.0
    timed_out: bool = False
    error: str = ""

    @property
    def ran(self) -> bool:
        """True if the fixed training script produced a usable validation metric."""
        return not self.timed_out and not self.error and "val_loss" in self.metrics


def _truncate(text: str, limit: int) -> str:
    return text if len(text) <= limit else text[:limit] + "\n...[truncated]"


def _count_expected_tests(tests_path: Path) -> int:
    """Cheap upper bound on the number of tests, by counting ``def test_`` lines.

    Used as the failure count when a candidate can't even be collected (e.g. a
    syntax error), so a broken candidate scores below one that runs and fails.
    """
    try:
        text = tests_path.read_text(encoding="utf-8")
    except OSError:
        return 0
    return len(re.findall(r"^\s*def\s+test_\w+", text, flags=re.MULTILINE))


def _parse_junit(report_path: Path) -> tuple[int, int] | None:
    """Return ``(passed, failed)`` parsed from a JUnit XML report, or ``None``."""
    if not report_path.exists():
        return None
    try:
        root = ElementTree.parse(report_path).getroot()
    except ElementTree.ParseError:
        return None
    suites = [root] if root.tag == "testsuite" else root.findall("testsuite")
    total = failures = errors = skipped = 0
    for suite in suites:
        total += int(suite.get("tests", 0))
        failures += int(suite.get("failures", 0))
        errors += int(suite.get("errors", 0))
        skipped += int(suite.get("skipped", 0))
    passed = total - failures - errors - skipped
    return max(passed, 0), failures + errors


class Sandbox:
    """Isolated runner for candidate code: temp dir, scrubbed env, hard timeout, no net."""

    def __init__(self, config: SandboxConfig | None = None) -> None:
        self.config = config or SandboxConfig()

    def child_env(self) -> dict[str, str]:
        """Environment for a candidate subprocess: credentials scrubbed."""
        return scrub_execution_env()

    def run(self, candidate, task, tests_path=None) -> SandboxResult:  # noqa: ANN001
        """Run a candidate's tests in isolation and return a :class:`SandboxResult`.

        ``candidate`` supplies only its ``code`` (written to the task's module file);
        ``task`` supplies the fixed ``module_name``. The test suite always comes from
        a controller-chosen file on disk, never from the candidate: by default the
        task's visible ``tests_path``, or an explicit ``tests_path`` override — which
        is how the hidden-test gate runs a held-out suite the candidate never saw
        (``docs/05_evaluation_and_safety_gates.md``).
        """
        suite_path = Path(tests_path) if tests_path is not None else Path(task.tests_path)
        env = self.child_env()
        assert_execution_plane_isolated(env)  # belt-and-suspenders: never run with creds

        with TemporaryDirectory(prefix="siro-sandbox-") as tmp:
            tmpdir = Path(tmp)
            (tmpdir / f"{task.module_name}.py").write_text(candidate.code, encoding="utf-8")
            (tmpdir / "tests.py").write_text(
                suite_path.read_text(encoding="utf-8"), encoding="utf-8"
            )
            (tmpdir / "sitecustomize.py").write_text(_SITECUSTOMIZE, encoding="utf-8")
            report_path = tmpdir / "report.xml"

            # The temp dir on PYTHONPATH makes both the candidate module and the
            # network-blocking sitecustomize importable at interpreter startup.
            env["PYTHONPATH"] = str(tmpdir)
            cmd = [
                sys.executable,
                "-m",
                "pytest",
                "tests.py",
                "-p",
                "no:cacheprovider",
                "-q",
                f"--junitxml={report_path}",
            ]

            start = time.perf_counter()
            try:
                proc = subprocess.run(
                    cmd,
                    cwd=tmpdir,
                    env=env,
                    capture_output=True,
                    text=True,
                    timeout=self.config.timeout_seconds,
                )
            except subprocess.TimeoutExpired as exc:
                runtime_ms = (time.perf_counter() - start) * 1000.0
                return SandboxResult(
                    returncode=-1,
                    stdout=_truncate(exc.stdout or "", self.config.max_output_bytes),
                    stderr=_truncate(exc.stderr or "", self.config.max_output_bytes),
                    runtime_ms=runtime_ms,
                    passed_tests=0,
                    failed_tests=_count_expected_tests(suite_path),
                    timed_out=True,
                    error=f"timeout after {self.config.timeout_seconds}s",
                )
            runtime_ms = (time.perf_counter() - start) * 1000.0

            parsed = _parse_junit(report_path)
            expected = _count_expected_tests(suite_path)
            if parsed is None:
                # No report at all: count every test as failed; not a real run.
                passed, failed = 0, expected
                error = "no test report produced"
            else:
                passed, failed = parsed
                if passed == 0 and proc.returncode != 0 and failed < expected:
                    # Collection/import error (e.g. syntax error): none of the real
                    # tests ran. Count them all as failed so a broken candidate scores
                    # below any candidate that runs, and mark the run non-reproducible.
                    passed, failed = 0, expected
                    error = "collection error: candidate could not be imported"
                else:
                    error = ""

            return SandboxResult(
                returncode=proc.returncode,
                stdout=_truncate(proc.stdout, self.config.max_output_bytes),
                stderr=_truncate(proc.stderr, self.config.max_output_bytes),
                runtime_ms=runtime_ms,
                passed_tests=passed,
                failed_tests=failed,
                error=error,
            )


    def run_training(self, config: dict, budget_seconds: float, *, script_path=None) -> TrainingRun:  # noqa: ANN001
        """Run the *fixed* training script under a candidate ``config`` in isolation.

        Same execution-plane contract as :meth:`run`: a temp dir, a credential-scrubbed
        env, the network-blocking ``sitecustomize``, and a hard subprocess timeout. The
        candidate supplies only ``config`` (hyperparameters, written as data); the script
        itself is controller-owned (``training_task.py``) and never candidate-editable.

        The wall-clock budget is enforced twice: cooperatively (passed to the script as
        ``_budget_seconds`` so it stops cleanly and reports a partial result) and hard (the
        subprocess timeout = ``budget_seconds`` + grace kills a script that ignores it).
        """
        script = Path(script_path) if script_path is not None else Path(__file__).with_name("training_task.py")
        env = self.child_env()
        assert_execution_plane_isolated(env)
        payload = dict(config)
        payload["_budget_seconds"] = budget_seconds
        # Hard ceiling: a few seconds past the cooperative budget, then the kernel timeout.
        hard_timeout = budget_seconds + 5.0

        with TemporaryDirectory(prefix="siro-train-") as tmp:
            tmpdir = Path(tmp)
            run_script = tmpdir / "training_task.py"
            shutil.copyfile(script, run_script)
            (tmpdir / "sitecustomize.py").write_text(_SITECUSTOMIZE, encoding="utf-8")
            config_path = tmpdir / "config.json"
            config_path.write_text(json.dumps(payload), encoding="utf-8")

            env["PYTHONPATH"] = str(tmpdir)
            cmd = [sys.executable, str(run_script), str(config_path)]
            start = time.perf_counter()
            try:
                proc = subprocess.run(
                    cmd,
                    cwd=tmpdir,
                    env=env,
                    capture_output=True,
                    text=True,
                    timeout=hard_timeout,
                )
            except subprocess.TimeoutExpired:
                runtime_ms = (time.perf_counter() - start) * 1000.0
                return TrainingRun(
                    runtime_ms=runtime_ms,
                    timed_out=True,
                    error=f"training exceeded hard timeout of {hard_timeout}s",
                )
            runtime_ms = (time.perf_counter() - start) * 1000.0

            if proc.returncode != 0:
                return TrainingRun(
                    runtime_ms=runtime_ms,
                    error=_truncate(proc.stderr or "training script failed", self.config.max_output_bytes),
                )
            line = proc.stdout.strip().splitlines()[-1] if proc.stdout.strip() else ""
            try:
                metrics = json.loads(line)
            except (json.JSONDecodeError, IndexError):
                return TrainingRun(runtime_ms=runtime_ms, error="training produced no parseable metrics")
            if "error" in metrics:
                return TrainingRun(runtime_ms=runtime_ms, metrics=metrics, error=str(metrics["error"]))
            return TrainingRun(metrics=metrics, runtime_ms=runtime_ms)


__all__ = ["SandboxConfig", "SandboxResult", "TrainingRun", "Sandbox"]
